/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.90
 * Generated at: 2023-08-03 11:58:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Iterator;
import jtc.Questions.Question;
import java.util.List;

public final class delete_005fquestion_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1687603148830L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("jtc.Questions.Question");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>COFEPOSA</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"keywords\" content=\"\">\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(e) {\r\n");
      out.write("    var $input = $('#refresh');\r\n");
      out.write("\r\n");
      out.write("    $input.val() == 'yes' ? location.reload(true) : $input.val('yes');\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"wrap\">\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("        <div class=\"slide\">\r\n");
      out.write("            <img src=\"images/slid.jpg\" alt=\"slide\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"nav\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                    <li><a href=\"index.jsp\">HOME</a></li>\r\n");
      out.write("                    <li><a href=\"About.jsp\">ABOUT US</a></li>\r\n");
      out.write("                    <li><a href=\"ContactUs.jsp\">CONTACT US</a></li>\r\n");
      out.write("<!--                 <li><a href=\"#\">Enter</a></li> -->\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"clear\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"left-side\">\r\n");
      out.write("				<div class=\"heading\">\r\n");
      out.write("					<h5>Login and Registration</h5>\r\n");
      out.write("				</div>\r\n");
      out.write("				<ul>\r\n");
      out.write("\r\n");
      out.write("					<li><span>&#9733;</span><a href=\"addQuestion.jsp\">Add\r\n");
      out.write("							Questions</a></li>\r\n");
      out.write("					<li><span>&#9733;</span><a href=\"createPaper.jsp\">Create\r\n");
      out.write("							Question Paper</a></li>\r\n");
      out.write("					<li><span>&#9733;</span><a href=\"showQuestion.jsp\">Show\r\n");
      out.write("							Questions</a></li>\r\n");
      out.write("					<li><a href=\"logout.jsp\"><button>Logout</button></a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"box2\">\r\n");
      out.write("				");

					String err_msg = (String) request.getAttribute("Err_Msg");
					if (err_msg != null) {
						
      out.write("\r\n");
      out.write("						<h3 style=\"color: #FF0000;\">\r\n");
      out.write("						");

						out.print(err_msg);
						
      out.write("\r\n");
      out.write("					</h3>\r\n");
      out.write("					");
 
					} else {
					
      out.write("\r\n");
      out.write("					\r\n");
      out.write("\r\n");
      out.write("				<table border=1>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>Question</th>\r\n");
      out.write("						<th>DOQ</th>\r\n");
      out.write("						<th>Module</th>\r\n");
      out.write("						<th>Subject</th>\r\n");
      out.write("						<th>Semester</th>\r\n");
      out.write("						<th>Branch</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("					");
 List<Question> questions = (List<Question>) (session.getAttribute("Questions")); 
					Iterator<Question> iterator = questions.iterator();
					while(iterator.hasNext()){
						Question question = iterator.next();
					
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>");
out.print(question.getQuestion());
      out.write("</td>\r\n");
      out.write("						<td>");
out.print(question.getDifficulty());
      out.write("</td>\r\n");
      out.write("						<td>");
out.print(question.getModule());
      out.write("</td>\r\n");
      out.write("						<td>");
out.print(question.getSubject());
      out.write("</td>\r\n");
      out.write("						<td>");
out.print(question.getSemester());
      out.write("</td>\r\n");
      out.write("						<td>");
out.print(question.getBranch());
      out.write("</td>\r\n");
      out.write("						<td><form action=\"UserController\" method=\"post\">\r\n");
      out.write("									<input type=\"hidden\" value=\"deleteQuestion\"\r\n");
      out.write("										name=\"actionRequest\">\r\n");
      out.write("										");
 String que = question.getQuestion();
										
      out.write(" <input type=\"hidden\"\r\n");
      out.write("										value=\"");
      out.print(que);
      out.write("\" name=\"question\"> <input\r\n");
      out.write("										type=\"submit\" value=\"DELETE\">\r\n");
      out.write("										<input type=\"hidden\" id=\"refresh\" value=\"no\">\r\n");
      out.write("								</form></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				\r\n");
}} 
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"clear\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"footer\">\r\n");
      out.write("			<h4>Designed And Developed\r\n");
      out.write("				By sanjeev.</h4>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
