/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.90
 * Generated at: 2023-07-31 18:51:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class showQuestion_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/headerHome.jsp", Long.valueOf(1687603148935L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>COEPOSA</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"keywords\" content=\"\">\r\n");
      out.write("<link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"wrap\">\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("            <img src=\"images/logo.png\" alt=\"logo\">\r\n");
      out.write("            <div id=\"success\">\r\n");
      out.write("            	<h3>");
      out.print("Welcome: " + session.getAttribute("Name"));
      out.write("</h3>\r\n");
      out.write("            	<p><form action=\"UserController\" method=\"post\">\r\n");
      out.write("            		<input type=\"hidden\" name=\"actionRequest\" value=\"logout\">\r\n");
      out.write("            		<input type=\"submit\" value=\"Logout\">\r\n");
      out.write("            	</form>\r\n");
      out.write("            	</p>\r\n");
      out.write("            </div>\r\n");
      out.write("             <div class=\"clear\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"slide\">\r\n");
      out.write("            <img src=\"images/slid.jpg\" alt=\"slide\">\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"nav\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                    <li><a href=\"home.jsp\">HOME</a></li>\r\n");
      out.write("                    <li><a href=\"#\">ABOUT US</a></li>\r\n");
      out.write("                    <li><a href=\"#\">CONTACT US</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"clear\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"left-side\">\r\n");
      out.write("				<div class=\"heading\">\r\n");
      out.write("					<h5>Login and Registration</h5>\r\n");
      out.write("				</div>\r\n");
      out.write("				<ul>\r\n");
      out.write("\r\n");
      out.write("					<li><span>&#9733;</span><a href=\"addQuestion.jsp\">Add\r\n");
      out.write("							Questions</a></li>\r\n");
      out.write("					<li><span>&#9733;</span><a href=\"set_question_type.jsp\">Create\r\n");
      out.write("							Question Paper</a></li>\r\n");
      out.write("					<li><span>&#9733;</span><a href=\"showQuestion.jsp\">Show\r\n");
      out.write("							Questions</a></li>\r\n");
      out.write("					<li><a href=\"logout.jsp\"><button>Logout</button></a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"box2\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"form\">\r\n");
      out.write("					<h2>Questions</h2>\r\n");
      out.write("					<form id=\"qlist\" action=\"UserController\" method=\"post\">\r\n");
      out.write("						<table>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td></td>\r\n");
      out.write("								<td><input type=\"hidden\" name=\"actionRequest\"\r\n");
      out.write("									value=\"showQuestion\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td><span>&#9733;</span><label for=\"branch\">Paper\r\n");
      out.write("										For Branch:</label></td>\r\n");
      out.write("								<td><select name=\"branch\" id=\"branch\">\r\n");
      out.write("										<option value=\"none\">--Select--</option>\r\n");
      out.write("										<option value=\"CS\">B.Tech CS</option>\r\n");
      out.write("										<option value=\"IT\">B.Tech IT</option>\r\n");
      out.write("										<option value=\"EC\">B.Tech EC</option>\r\n");
      out.write("										<option value=\"MCA\">MCA</option>\r\n");
      out.write("\r\n");
      out.write("								</select></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td><span>&#9733;</span><label for=\"semester\">Semester:</label></td>\r\n");
      out.write("								<td><select name=\"semester\" id=\"semester\">\r\n");
      out.write("										<option value=\"none\">--Select--</option>\r\n");
      out.write("										<option value=\"1\">1</option>\r\n");
      out.write("										<option value=\"2\">2</option>\r\n");
      out.write("										<option value=\"3\">3</option>\r\n");
      out.write("										<option value=\"4\">4</option>\r\n");
      out.write("										<option value=\"5\">5</option>\r\n");
      out.write("										<option value=\"6\">6</option>\r\n");
      out.write("										<option value=\"7\">7</option>\r\n");
      out.write("										<option value=\"8\">8</option>\r\n");
      out.write("								</select></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td><span>&#9733;</span><label for=\"subject\">Subject:</label></td>\r\n");
      out.write("								<td><select name=\"subject\" id=\"subject\">\r\n");
      out.write("										<option value=\"none\">--Select--</option>\r\n");
      out.write("										<option value=\"OS\">Operating System</option>\r\n");
      out.write("										<option value=\"NW\">Networking</option>\r\n");
      out.write("										<option value=\"DS\">Data Structure</option>\r\n");
      out.write("										<option value=\"DB\">Database</option>\r\n");
      out.write("										<option value=\"Java\">Java</option>\r\n");
      out.write("										<option value=\"C\">C</option>\r\n");
      out.write("										<option value=\"CPP\">CPP</option>\r\n");
      out.write("								</select></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td></td>\r\n");
      out.write("								<td><input class=\"buttom\" name=\"submit\" id=\"submit\"\r\n");
      out.write("									value=\"Show\" type=\"submit\"></td>\r\n");
      out.write("							</tr>\r\n");
      out.write("\r\n");
      out.write("						</table>\r\n");
      out.write("					</form>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"clear\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"footer\">\r\n");
      out.write("			<h4>Designed And Developed\r\n");
      out.write("				By sanjeev.</h4>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
